---
version: "3.4"

######################################
### Used for running rspec against ###
######################################

services:
  neo4j-http-test-container:
    image: neo4j:4.3.5-enterprise
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
      - "7484:7484"
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: "none"
      NEO4J_dbms_allow__upgrade: "true"
      NEO4J_dbms_jvm_additional: "-Xms256m -Xmx256m"
      NEO4J_dbms_logs_query_enabled: "true"
      NEO4J_dbms_memory_heap_max__size: "256M"
      NEO4J_dbms_memory_pagecache_size: "256M"
    volumes:
      - neo4j-http-test-volume:/data

volumes:
  neo4j-http-test-volume:
